apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ack-ecr-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aws-controllers-k8s/ecr-controller.git
    targetRevision: main
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true