apiVersion: ecr.services.k8s.aws/v1
kind: Repository
metadata:
  name: todo-app-repo
  namespace: kube-system
spec:
  repositoryName: todo-app
  imageTagMutability: MUTABLE
  lifecyclePolicy:
    rules:
      - rulePriority: 1
        selection:
          tagStatus: TAGGED
        action:
          type: EXPIRY
          expiry: 30 