apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/georgejohnis/todoapp-platform-infra.git
    targetRevision: main
    path: kubernetes/infrastructure/ecr
    helm:
      releaseName: ack-ecr-controller
      values: |
        serviceAccount:
          create: true
          name: ack-ecr-controller
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/ack-ecr-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://aws.github.io/eks-charts
      chart: ack-ecr-controller
      targetRevision: "1.1.0"
      helm:
        releaseName: ack-ecr-controller
        values: |
          serviceAccount:
            create: true
            name: ack-ecr-controller
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/ack-ecr-controller 