apiVersion: ecr.services.k8s.aws/v1alpha1
kind: Repository
metadata:
  name: todo-app-repo
  namespace: kube-system
  labels:
    app: todo-app
    managed-by: platform-team
spec:
  name: todo-app
  repositoryName: todo-app
  imageTagMutability: MUTABLE
  lifecyclePolicy: |
    {
      "rules": [
        {
          "rulePriority": 1,
          "selection": {
            "tagStatus": "TAGGED"
          },
          "action": {
            "type": "EXPIRE",
            "days": 30
          }
        }
      ]
    }